name: build-without-patch

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: build x64
    runs-on: ubuntu-latest
    env:
      Output: "${{ github.workspace }}/x64"
      RID: win-x64
      Project: './v2rayN/v2rayN.csproj'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build v2rayN
      working-directory: ./v2rayN
      run: dotnet publish $Project -c Release -r $RID -p:SelfContained=true -p:EnableWindowsTargeting=true -o $Output
      env:
        NUGET_CERT_REVOCATION_MODE: offline

    - name: Build AmazTool
      working-directory: ./v2rayN
      run: dotnet publish ./AmazTool/AmazTool.csproj -c Release -r $RID -p:SelfContained=true -p:PublishTrimmed=true -p:EnableWindowsTargeting=true -o $Output
      env:
        NUGET_CERT_REVOCATION_MODE: offline

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: v2rayN-windows-x64
        path: x64
