name: commit patch

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  apply-patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Apply patch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "Checking patch..."
          git apply --check v2rayN-outbound-interface-fixed.patch

          echo "Applying patch..."
          git apply v2rayN-outbound-interface-fixed.patch

          echo "Removing patch file..."
          rm v2rayN-outbound-interface-fixed.patch

      - name: Commit changes
        run: |
          git add .
          git commit -m "v-7.21.2_commit_pach_v03"
          git push
