name: Rename commit

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rename:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update commit message and touch v2rayN folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # ایجاد marker داخل پوشه v2rayN
          echo "v-7.21.2_commit_pach" > v2rayN/.patch-version

          git add v2rayN/.patch-version

          # تغییر پیام آخرین commit
          git commit --amend -m "v-7.21.2_commit_pach_v02"

          # push با بازنویسی تاریخچه
          git push --force
